name: Generate web site

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install cpanm
      run: |
          sudo apt-get update -y
          sudo apt-get install -y cpanminus
    - name: Install useful libraries
      run: |
          sudo apt-get install -y libssl-dev libz-dev
    - name: Install modules
      run: |
          sudo cpanm --notest File::ShareDir::Install
          sudo cpanm --installdeps --notest .
          sudo cpanm --notest App::CPANModuleSite
    - name: Create pages
      run: |
        echo Building site...
        /usr/local/bin/mksite App-CPANModuleSite /app-cpanmodulesite
    - name: Commit new page
      run: |
        GIT_STATUS=$(git status --porcelain)
        echo $GIT_STATUS
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add docs/
        if [ "$GIT_STATUS" != "" ]; then git commit -m "Web site generation"; fi
        if [ "$GIT_STATUS" != "" ]; then git push; fi
    - name: Archive CPAN logs
      if: ${{ failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: cpan_log
        path: .cpanm/work/*/build.log
        retention-days: 2
