name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest' ]
        perl: [ 'latest' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - run: cpanm --notest File::ShareDir::Install
      - run: cpanm --notest --installdeps .
      - run: prove -lv t
      - name: Archive CPAN logs on Windows
        if: ${{ failure() }} && runner.os == 'Windows'
        uses: actions/upload-artifact@v3
        with:
          name: cpan_log
          path: C:\Users\RUNNER~1\.cpanm\work\*\build.log
      - name: Archive CPAN logs on non-Windows
        if: ${{ failure() }} && runner.os != 'Windows'
        uses: actions/upload-artifact@v3
        with:
          name: cpan_log
          path: $HOME/.cpanm/work/*/build.log

  coverage:
    runs-on: ubuntu-latest
    container: davorg/perl-coveralls:latest
    name: Test coverage
    steps:
      - uses: actions/checkout@v3
      - run: cpanm --notest File::ShareDir::Install
      - run: cpanm --notest --installdeps .
      - name: Install modules
        run: cpanm -n --installdeps .
      - name: Coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cover -test -report Coveralls

  perlcritic:
    uses: PerlToolsTeam/github_workflows/.github/workflows/cpan-perlcritic.yml@main

  complexity:
    uses: PerlToolsTeam/github_workflows/.github/workflows/cpan-complexity.yml@main

